// Reusable export service — CSV & PDF (via printable window). Excel-ready interface.

export type ExportColumn<T = any> = {
  key: keyof T | string;
  label: string;
  format?: (v: any, row: T) => string | number;
};

function csvEscape(v: unknown): string {
  if (v === null || v === undefined) return "";
  const s = String(v);
  if (/[",\n\r]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
  return s;
}

function trigger(blob: Blob, filename: string) {
  if (typeof window === "undefined") return;
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 500);
}

export function exportCSV<T>(filename: string, columns: ExportColumn<T>[], rows: T[]) {
  const header = columns.map((c) => csvEscape(c.label)).join(",");
  const body = rows
    .map((r) =>
      columns
        .map((c) => {
          const raw = (r as any)[c.key];
          const val = c.format ? c.format(raw, r) : raw;
          return csvEscape(val);
        })
        .join(","),
    )
    .join("\n");
  const csv = `${header}\n${body}`;
  trigger(new Blob([csv], { type: "text/csv;charset=utf-8" }), filename.endsWith(".csv") ? filename : `${filename}.csv`);
}

export function exportPDF<T>(opts: {
  title: string;
  subtitle?: string;
  columns: ExportColumn<T>[];
  rows: T[];
  meta?: Record<string, string | number>;
}) {
  if (typeof window === "undefined") return;
  const { title, subtitle, columns, rows, meta } = opts;
  const w = window.open("", "_blank", "width=900,height=700");
  if (!w) return;
  const headerCells = columns.map((c) => `<th>${escapeHtml(c.label)}</th>`).join("");
  const bodyRows = rows
    .map(
      (r) =>
        `<tr>${columns
          .map((c) => {
            const raw = (r as any)[c.key];
            const v = c.format ? c.format(raw, r) : raw;
            return `<td>${escapeHtml(v ?? "")}</td>`;
          })
          .join("")}</tr>`,
    )
    .join("");
  const metaHtml = meta
    ? `<div class="meta">${Object.entries(meta)
        .map(([k, v]) => `<div><span>${escapeHtml(k)}</span><strong>${escapeHtml(v)}</strong></div>`)
        .join("")}</div>`
    : "";
  w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(title)}</title>
<style>
  *{box-sizing:border-box} body{font:13px/1.4 -apple-system,BlinkMacSystemFont,Segoe UI,sans-serif;color:#111;padding:32px;margin:0}
  h1{font-size:20px;margin:0 0 4px} .sub{color:#666;margin-bottom:16px}
  .meta{display:flex;gap:24px;flex-wrap:wrap;border:1px solid #e5e7eb;border-radius:8px;padding:12px 16px;margin-bottom:20px}
  .meta>div{display:flex;flex-direction:column} .meta span{font-size:11px;color:#666;text-transform:uppercase;letter-spacing:.5px}
  .meta strong{font-size:14px;margin-top:2px}
  table{width:100%;border-collapse:collapse;font-size:12px}
  th,td{text-align:left;padding:8px 10px;border-bottom:1px solid #e5e7eb}
  th{background:#f9fafb;font-weight:600;text-transform:uppercase;font-size:10px;letter-spacing:.5px;color:#374151}
  tr:nth-child(even) td{background:#fafafa}
  .footer{margin-top:24px;font-size:11px;color:#999;text-align:right}
  @media print{body{padding:16px}}
</style></head><body>
<h1>${escapeHtml(title)}</h1>
${subtitle ? `<div class="sub">${escapeHtml(subtitle)}</div>` : ""}
${metaHtml}
<table><thead><tr>${headerCells}</tr></thead><tbody>${bodyRows}</tbody></table>
<div class="footer">Generated by TailorERP · ${new Date().toLocaleString()}</div>
<script>window.onload=()=>{setTimeout(()=>window.print(),250)}</script>
</body></html>`);
  w.document.close();
}

function escapeHtml(v: unknown) {
  return String(v ?? "").replace(/[&<>"']/g, (m) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[m] as string));
}

// Placeholder for future native Excel export (xlsx). Falls back to CSV today.
export function exportExcel<T>(filename: string, columns: ExportColumn<T>[], rows: T[]) {
  exportCSV(filename, columns, rows);
}
