/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as TenantSettingsRouteImport } from './routes/tenant-settings'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SessionExpiredRouteImport } from './routes/session-expired'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportsCenterRouteImport } from './routes/reports-center'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProductionRouteImport } from './routes/production'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as OrganizationRouteImport } from './routes/organization'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MeasurementsRouteImport } from './routes/measurements'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DesignsRouteImport } from './routes/designs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunicationsRouteImport } from './routes/communications'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as BookDemoRouteImport } from './routes/book-demo'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as PortalProfileRouteImport } from './routes/portal.profile'
import { Route as PortalOrdersRouteImport } from './routes/portal.orders'
import { Route as PortalMeasurementsRouteImport } from './routes/portal.measurements'
import { Route as PortalLoginRouteImport } from './routes/portal.login'
import { Route as PortalInvoicesRouteImport } from './routes/portal.invoices'
import { Route as PortalDashboardRouteImport } from './routes/portal.dashboard'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as DocsDeploymentRouteImport } from './routes/docs.deployment'
import { Route as DocsApiRouteImport } from './routes/docs.api'
import { Route as CustomersIdRouteImport } from './routes/customers.$id'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantSettingsRoute = TenantSettingsRouteImport.update({
  id: '/tenant-settings',
  path: '/tenant-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionExpiredRoute = SessionExpiredRouteImport.update({
  id: '/session-expired',
  path: '/session-expired',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsCenterRoute = ReportsCenterRouteImport.update({
  id: '/reports-center',
  path: '/reports-center',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionRoute = ProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationRoute = OrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MeasurementsRoute = MeasurementsRouteImport.update({
  id: '/measurements',
  path: '/measurements',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignsRoute = DesignsRouteImport.update({
  id: '/designs',
  path: '/designs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationsRoute = CommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const BookDemoRoute = BookDemoRouteImport.update({
  id: '/book-demo',
  path: '/book-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRoute,
} as any)
const PortalOrdersRoute = PortalOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMeasurementsRoute = PortalMeasurementsRouteImport.update({
  id: '/measurements',
  path: '/measurements',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PortalRoute,
} as any)
const PortalInvoicesRoute = PortalInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDashboardRoute = PortalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PortalRoute,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrdersRoute,
} as any)
const DocsDeploymentRoute = DocsDeploymentRouteImport.update({
  id: '/deployment',
  path: '/deployment',
  getParentRoute: () => DocsRoute,
} as any)
const DocsApiRoute = DocsApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => DocsRoute,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audit-logs': typeof AuditLogsRoute
  '/billing': typeof BillingRoute
  '/book-demo': typeof BookDemoRoute
  '/branches': typeof BranchesRoute
  '/communications': typeof CommunicationsRoute
  '/contact': typeof ContactRoute
  '/designs': typeof DesignsRoute
  '/docs': typeof DocsRouteWithChildren
  '/employees': typeof EmployeesRoute
  '/features': typeof FeaturesRoute
  '/finance': typeof FinanceRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/inventory': typeof InventoryRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/measurements': typeof MeasurementsRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRouteWithChildren
  '/organization': typeof OrganizationRoute
  '/portal': typeof PortalRouteWithChildren
  '/pricing': typeof PricingRoute
  '/production': typeof ProductionRoute
  '/reports': typeof ReportsRoute
  '/reports-center': typeof ReportsCenterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roles': typeof RolesRoute
  '/session-expired': typeof SessionExpiredRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/subscription': typeof SubscriptionRoute
  '/super-admin': typeof SuperAdminRoute
  '/tenant-settings': typeof TenantSettingsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/customers/$id': typeof CustomersIdRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/deployment': typeof DocsDeploymentRoute
  '/orders/$id': typeof OrdersIdRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/invoices': typeof PortalInvoicesRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/measurements': typeof PortalMeasurementsRoute
  '/portal/orders': typeof PortalOrdersRoute
  '/portal/profile': typeof PortalProfileRoute
  '/customers/': typeof CustomersIndexRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audit-logs': typeof AuditLogsRoute
  '/billing': typeof BillingRoute
  '/book-demo': typeof BookDemoRoute
  '/branches': typeof BranchesRoute
  '/communications': typeof CommunicationsRoute
  '/contact': typeof ContactRoute
  '/designs': typeof DesignsRoute
  '/employees': typeof EmployeesRoute
  '/features': typeof FeaturesRoute
  '/finance': typeof FinanceRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/inventory': typeof InventoryRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/measurements': typeof MeasurementsRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRouteWithChildren
  '/organization': typeof OrganizationRoute
  '/portal': typeof PortalRouteWithChildren
  '/pricing': typeof PricingRoute
  '/production': typeof ProductionRoute
  '/reports': typeof ReportsRoute
  '/reports-center': typeof ReportsCenterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roles': typeof RolesRoute
  '/session-expired': typeof SessionExpiredRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/subscription': typeof SubscriptionRoute
  '/super-admin': typeof SuperAdminRoute
  '/tenant-settings': typeof TenantSettingsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/customers/$id': typeof CustomersIdRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/deployment': typeof DocsDeploymentRoute
  '/orders/$id': typeof OrdersIdRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/invoices': typeof PortalInvoicesRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/measurements': typeof PortalMeasurementsRoute
  '/portal/orders': typeof PortalOrdersRoute
  '/portal/profile': typeof PortalProfileRoute
  '/customers': typeof CustomersIndexRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audit-logs': typeof AuditLogsRoute
  '/billing': typeof BillingRoute
  '/book-demo': typeof BookDemoRoute
  '/branches': typeof BranchesRoute
  '/communications': typeof CommunicationsRoute
  '/contact': typeof ContactRoute
  '/designs': typeof DesignsRoute
  '/docs': typeof DocsRouteWithChildren
  '/employees': typeof EmployeesRoute
  '/features': typeof FeaturesRoute
  '/finance': typeof FinanceRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/inventory': typeof InventoryRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/measurements': typeof MeasurementsRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRouteWithChildren
  '/organization': typeof OrganizationRoute
  '/portal': typeof PortalRouteWithChildren
  '/pricing': typeof PricingRoute
  '/production': typeof ProductionRoute
  '/reports': typeof ReportsRoute
  '/reports-center': typeof ReportsCenterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roles': typeof RolesRoute
  '/session-expired': typeof SessionExpiredRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/subscription': typeof SubscriptionRoute
  '/super-admin': typeof SuperAdminRoute
  '/tenant-settings': typeof TenantSettingsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/customers/$id': typeof CustomersIdRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/deployment': typeof DocsDeploymentRoute
  '/orders/$id': typeof OrdersIdRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/invoices': typeof PortalInvoicesRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/measurements': typeof PortalMeasurementsRoute
  '/portal/orders': typeof PortalOrdersRoute
  '/portal/profile': typeof PortalProfileRoute
  '/customers/': typeof CustomersIndexRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/audit-logs'
    | '/billing'
    | '/book-demo'
    | '/branches'
    | '/communications'
    | '/contact'
    | '/designs'
    | '/docs'
    | '/employees'
    | '/features'
    | '/finance'
    | '/forgot-password'
    | '/help'
    | '/inventory'
    | '/landing'
    | '/login'
    | '/measurements'
    | '/notifications'
    | '/onboarding'
    | '/orders'
    | '/organization'
    | '/portal'
    | '/pricing'
    | '/production'
    | '/reports'
    | '/reports-center'
    | '/reset-password'
    | '/roles'
    | '/session-expired'
    | '/settings'
    | '/status'
    | '/subscription'
    | '/super-admin'
    | '/tenant-settings'
    | '/unauthorized'
    | '/customers/$id'
    | '/docs/api'
    | '/docs/deployment'
    | '/orders/$id'
    | '/portal/dashboard'
    | '/portal/invoices'
    | '/portal/login'
    | '/portal/measurements'
    | '/portal/orders'
    | '/portal/profile'
    | '/customers/'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/audit-logs'
    | '/billing'
    | '/book-demo'
    | '/branches'
    | '/communications'
    | '/contact'
    | '/designs'
    | '/employees'
    | '/features'
    | '/finance'
    | '/forgot-password'
    | '/help'
    | '/inventory'
    | '/landing'
    | '/login'
    | '/measurements'
    | '/notifications'
    | '/onboarding'
    | '/orders'
    | '/organization'
    | '/portal'
    | '/pricing'
    | '/production'
    | '/reports'
    | '/reports-center'
    | '/reset-password'
    | '/roles'
    | '/session-expired'
    | '/settings'
    | '/status'
    | '/subscription'
    | '/super-admin'
    | '/tenant-settings'
    | '/unauthorized'
    | '/customers/$id'
    | '/docs/api'
    | '/docs/deployment'
    | '/orders/$id'
    | '/portal/dashboard'
    | '/portal/invoices'
    | '/portal/login'
    | '/portal/measurements'
    | '/portal/orders'
    | '/portal/profile'
    | '/customers'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/audit-logs'
    | '/billing'
    | '/book-demo'
    | '/branches'
    | '/communications'
    | '/contact'
    | '/designs'
    | '/docs'
    | '/employees'
    | '/features'
    | '/finance'
    | '/forgot-password'
    | '/help'
    | '/inventory'
    | '/landing'
    | '/login'
    | '/measurements'
    | '/notifications'
    | '/onboarding'
    | '/orders'
    | '/organization'
    | '/portal'
    | '/pricing'
    | '/production'
    | '/reports'
    | '/reports-center'
    | '/reset-password'
    | '/roles'
    | '/session-expired'
    | '/settings'
    | '/status'
    | '/subscription'
    | '/super-admin'
    | '/tenant-settings'
    | '/unauthorized'
    | '/customers/$id'
    | '/docs/api'
    | '/docs/deployment'
    | '/orders/$id'
    | '/portal/dashboard'
    | '/portal/invoices'
    | '/portal/login'
    | '/portal/measurements'
    | '/portal/orders'
    | '/portal/profile'
    | '/customers/'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuditLogsRoute: typeof AuditLogsRoute
  BillingRoute: typeof BillingRoute
  BookDemoRoute: typeof BookDemoRoute
  BranchesRoute: typeof BranchesRoute
  CommunicationsRoute: typeof CommunicationsRoute
  ContactRoute: typeof ContactRoute
  DesignsRoute: typeof DesignsRoute
  DocsRoute: typeof DocsRouteWithChildren
  EmployeesRoute: typeof EmployeesRoute
  FeaturesRoute: typeof FeaturesRoute
  FinanceRoute: typeof FinanceRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  InventoryRoute: typeof InventoryRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  MeasurementsRoute: typeof MeasurementsRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  OrganizationRoute: typeof OrganizationRoute
  PortalRoute: typeof PortalRouteWithChildren
  PricingRoute: typeof PricingRoute
  ProductionRoute: typeof ProductionRoute
  ReportsRoute: typeof ReportsRoute
  ReportsCenterRoute: typeof ReportsCenterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RolesRoute: typeof RolesRoute
  SessionExpiredRoute: typeof SessionExpiredRoute
  SettingsRoute: typeof SettingsRoute
  StatusRoute: typeof StatusRoute
  SubscriptionRoute: typeof SubscriptionRoute
  SuperAdminRoute: typeof SuperAdminRoute
  TenantSettingsRoute: typeof TenantSettingsRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  CustomersIdRoute: typeof CustomersIdRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant-settings': {
      id: '/tenant-settings'
      path: '/tenant-settings'
      fullPath: '/tenant-settings'
      preLoaderRoute: typeof TenantSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session-expired': {
      id: '/session-expired'
      path: '/session-expired'
      fullPath: '/session-expired'
      preLoaderRoute: typeof SessionExpiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports-center': {
      id: '/reports-center'
      path: '/reports-center'
      fullPath: '/reports-center'
      preLoaderRoute: typeof ReportsCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production': {
      id: '/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization': {
      id: '/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/measurements': {
      id: '/measurements'
      path: '/measurements'
      fullPath: '/measurements'
      preLoaderRoute: typeof MeasurementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designs': {
      id: '/designs'
      path: '/designs'
      fullPath: '/designs'
      preLoaderRoute: typeof DesignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communications': {
      id: '/communications'
      path: '/communications'
      fullPath: '/communications'
      preLoaderRoute: typeof CommunicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-demo': {
      id: '/book-demo'
      path: '/book-demo'
      fullPath: '/book-demo'
      preLoaderRoute: typeof BookDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/orders': {
      id: '/portal/orders'
      path: '/orders'
      fullPath: '/portal/orders'
      preLoaderRoute: typeof PortalOrdersRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/measurements': {
      id: '/portal/measurements'
      path: '/measurements'
      fullPath: '/portal/measurements'
      preLoaderRoute: typeof PortalMeasurementsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/invoices': {
      id: '/portal/invoices'
      path: '/invoices'
      fullPath: '/portal/invoices'
      preLoaderRoute: typeof PortalInvoicesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/dashboard': {
      id: '/portal/dashboard'
      path: '/dashboard'
      fullPath: '/portal/dashboard'
      preLoaderRoute: typeof PortalDashboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/docs/deployment': {
      id: '/docs/deployment'
      path: '/deployment'
      fullPath: '/docs/deployment'
      preLoaderRoute: typeof DocsDeploymentRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/api': {
      id: '/docs/api'
      path: '/api'
      fullPath: '/docs/api'
      preLoaderRoute: typeof DocsApiRouteImport
      parentRoute: typeof DocsRoute
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DocsRouteChildren {
  DocsApiRoute: typeof DocsApiRoute
  DocsDeploymentRoute: typeof DocsDeploymentRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsApiRoute: DocsApiRoute,
  DocsDeploymentRoute: DocsDeploymentRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface OrdersRouteChildren {
  OrdersIdRoute: typeof OrdersIdRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersIdRoute: OrdersIdRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface PortalRouteChildren {
  PortalDashboardRoute: typeof PortalDashboardRoute
  PortalInvoicesRoute: typeof PortalInvoicesRoute
  PortalLoginRoute: typeof PortalLoginRoute
  PortalMeasurementsRoute: typeof PortalMeasurementsRoute
  PortalOrdersRoute: typeof PortalOrdersRoute
  PortalProfileRoute: typeof PortalProfileRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalDashboardRoute: PortalDashboardRoute,
  PortalInvoicesRoute: PortalInvoicesRoute,
  PortalLoginRoute: PortalLoginRoute,
  PortalMeasurementsRoute: PortalMeasurementsRoute,
  PortalOrdersRoute: PortalOrdersRoute,
  PortalProfileRoute: PortalProfileRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuditLogsRoute: AuditLogsRoute,
  BillingRoute: BillingRoute,
  BookDemoRoute: BookDemoRoute,
  BranchesRoute: BranchesRoute,
  CommunicationsRoute: CommunicationsRoute,
  ContactRoute: ContactRoute,
  DesignsRoute: DesignsRoute,
  DocsRoute: DocsRouteWithChildren,
  EmployeesRoute: EmployeesRoute,
  FeaturesRoute: FeaturesRoute,
  FinanceRoute: FinanceRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  InventoryRoute: InventoryRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  MeasurementsRoute: MeasurementsRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  OrdersRoute: OrdersRouteWithChildren,
  OrganizationRoute: OrganizationRoute,
  PortalRoute: PortalRouteWithChildren,
  PricingRoute: PricingRoute,
  ProductionRoute: ProductionRoute,
  ReportsRoute: ReportsRoute,
  ReportsCenterRoute: ReportsCenterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RolesRoute: RolesRoute,
  SessionExpiredRoute: SessionExpiredRoute,
  SettingsRoute: SettingsRoute,
  StatusRoute: StatusRoute,
  SubscriptionRoute: SubscriptionRoute,
  SuperAdminRoute: SuperAdminRoute,
  TenantSettingsRoute: TenantSettingsRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  CustomersIdRoute: CustomersIdRoute,
  CustomersIndexRoute: CustomersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
